import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gray-100 flex justify-center items-center py-10 px-4`}>
        <div className="bg-white w-full max-w-md h-[80vh] rounded-2xl shadow-xl overflow-hidden flex flex-col">
          <header className="bg-primary text-white p-6 text-center shrink-0">
            <h1 className="text-2xl font-bold">My Todo (Next.js)</h1>
          </header>
          <main className="p-6 flex-1 overflow-hidden flex flex-col">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
